version: "3"
services:
  bun-hackathon_1:
    image: bun-hackathon
    command: "bun run start:dev"
    hostname: bun-hackathon_1
    volumes:
      - .:/usr/src/app
    depends_on:
      - "hackathon_db_24"
    expose:
      - "3002"
    networks:
      - bun-hackathon-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    environment:
      LISTEN_HOST: 0.0.0.0
      PORT: 3002
      MONGO_DB_NAME: "hackathon_db_24"
      MONGO_DB_URL: "mongodb://hackathon_db_24:27017/data"

  bun-hackathon_2:
    image: bun-hackathon
    command: "bun run start:dev"
    hostname: bun-hackathon_2
    volumes:
      - .:/usr/src/app
    depends_on:
      - "hackathon_db_24"
    expose:
      - "3002"
    networks:
      - bun-hackathon-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    environment:
      LISTEN_HOST: 0.0.0.0
      PORT: 3002
      MONGO_DB_NAME: "hackathon_db_24"
      MONGO_DB_URL: "mongodb://hackathon_db_24:27017/data"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bun-hackathon_1
      - bun-hackathon_2
    ports:
      - "4000:4000"
    networks:
      - bun-hackathon-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  hackathon_db_24:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bun-hackathon-network
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

volumes:
  mongo-data:

networks:
  bun-hackathon-network:
